version: "3.9"

services:
  jira-echo:
    image: yarche/jira-echo:${TAG:-local}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    environment:
      - PORT=80
      - PROJECT_ID=10545
      - ISSUE_TYPE_ID=10004
      - SECRET_USER=${SECRET_USER}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - JIRA_DNS=${JIRA_DNS:-jira-echo.requestcatcher.com}
    ports:
      - "80:80"
    command: ["node", "server.js"]
