version: "3.9"

services:
  jira-echo:
    image: yarche/jira-echo:${TAG:-local}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    environment:
      - PORT=80
      - PROJECT_ID_DEFAULT=10545
      - ISSUE_TYPE_ID=10004
      - JIRA_USER=${JIRA_USER}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - JIRA_DNS=${JIRA_DNS:-jira-echo.requestcatcher.com}
      - JIRA_ECHO_VERSION=local
    ports:
      - "80:80"
    command: ["node", "server.js"]
