name: docker build && push
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build
        env:
          TAG: ${{ github.ref_name }}
        run: |
          docker compose build jira-echo -t yarche/jira-echo:latest
          docker tag yarche/jira-echo:latest yarche/jira-echo:${GITHUB_SHA::7}
          docker tag yarche/jira-echo:latest yarche/jira-echo:${TAG}
      - name: docker push
        env:
          TAG: ${{ github.ref_name }}
        run: |
          docker push yarche/jira-echo:latest
          docker push yarche/jira-echo:${GITHUB_SHA::7}
          docker push yarche/jira-echo:${TAG}
